server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql//localhost:3306/llp?useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    注册服务
  application:
    name: orderService
  cloud:
    nacos:
      server-addr: localhost:8848
mybatis:
  type-aliases-package: com.example.pojo
  configuration:
    map-underscore-to-camel-case: true
